name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker:
    uses: andregoepel/workflows/.github/workflows/docker-image.yml@main
    with:
      image: ghcr.io/${{ github.repository }}
      dockerfile: ./src/AndreGoepel.FinanceApp/Dockerfile
    permissions:
      contents: read
      packages: write # push to GHCR via the built-in GITHUB_TOKEN
